# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_fun_DoublePois <- function(xseq, x, y, startv, startv2, kappa, nu, tol, maxit) {
    .Call(`_NPCirc_my_fun_DoublePois`, xseq, x, y, startv, startv2, kappa, nu, tol, maxit)
}

my_fun_loglik_cv_nu <- function(x, y, startv, startv2, kappa, nu) {
    .Call(`_NPCirc_my_fun_loglik_cv_nu`, x, y, startv, startv2, kappa, nu)
}

R_modereg_CircLin <- function(Y, X, T, kappa, h, max_it, tol) {
    .Call(`_NPCirc_R_modereg_CircLin`, Y, X, T, kappa, h, max_it, tol)
}

R_modereg_CircCirc <- function(Y, X, T, kappa1, kappa2, max_it, tol) {
    .Call(`_NPCirc_R_modereg_CircCirc`, Y, X, T, kappa1, kappa2, max_it, tol)
}

R_modereg_LinCirc <- function(Y, X, T, h, kappa, max_it, tol) {
    .Call(`_NPCirc_R_modereg_LinCirc`, Y, X, T, h, kappa, max_it, tol)
}

R_CV_modereg_CircLin2 <- function(Y, X, h1, h2, max_it, tol) {
    .Call(`_NPCirc_R_CV_modereg_CircLin2`, Y, X, h1, h2, max_it, tol)
}

R_re_CV_modereg_CircLin2 <- function(Y, X, h1, h2, max_it, tol) {
    .Call(`_NPCirc_R_re_CV_modereg_CircLin2`, Y, X, h1, h2, max_it, tol)
}

R_CV_modereg_LinCirc <- function(Y, X, h, kappa, max_it, tol) {
    .Call(`_NPCirc_R_CV_modereg_LinCirc`, Y, X, h, kappa, max_it, tol)
}

R_cv_re_modereg_LinCirc <- function(Y, X, h1, h2, max_it, tol) {
    .Call(`_NPCirc_R_cv_re_modereg_LinCirc`, Y, X, h1, h2, max_it, tol)
}

R_CV_grid_modereg_LinCirc <- function(Y, X, h1, h2, max_it, tol) {
    .Call(`_NPCirc_R_CV_grid_modereg_LinCirc`, Y, X, h1, h2, max_it, tol)
}

R_CV_modereg_CircCirc <- function(Y, X, kappa1, kappa2, max_it, tol) {
    .Call(`_NPCirc_R_CV_modereg_CircCirc`, Y, X, kappa1, kappa2, max_it, tol)
}

R_cv_re_modereg_CircCirc <- function(Y, X, kappa1, kappa2, max_it, tol) {
    .Call(`_NPCirc_R_cv_re_modereg_CircCirc`, Y, X, kappa1, kappa2, max_it, tol)
}

R_CV_grid_modereg_CircCirc <- function(Y, X, h1, h2, max_it, tol) {
    .Call(`_NPCirc_R_CV_grid_modereg_CircCirc`, Y, X, h1, h2, max_it, tol)
}

R_EM_vMN_select <- function(T, X, M, tolEM, maxitersEM, maxitersInit, rep) {
    .Call(`_NPCirc_R_EM_vMN_select`, T, X, M, tolEM, maxitersEM, maxitersInit, rep)
}

R_EM_vMvM_select <- function(T, X, M, tolEM, maxitersEM, maxitersInit, rep) {
    .Call(`_NPCirc_R_EM_vMvM_select`, T, X, M, tolEM, maxitersEM, maxitersInit, rep)
}

